# Generated by Django 3.0 on 2020-02-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200222_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='background_image',
        ),
    ]
