# Generated by Django 3.0 on 2020-02-24 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='mod_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
