# Generated by Django 3.0.3 on 2020-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200319_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogseries',
            old_name='blog',
            new_name='blogs',
        ),
    ]
