# Generated by Django 3.0.3 on 2020-03-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200319_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogSeries'),
        ),
    ]
